# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelList
	pod 'Alamofire'
	pod 'RxSwift', '~> 5'
        pod 'RxCocoa', '~> 5'
	pod 'Swinject'
	pod 'SwinjectAutoregistration'
	pod 'NVActivityIndicatorView'
	pod 'Nuke', '~> 7.0'

  target 'MarvelListTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
